import { Resend } from "resend";

export class WeeklySummary {
  constructor(stats) {
    this.stats = stats;
    this.resend = new Resend(process.env.RESEND_API_KEY);
  }

  async send() {
    const html = this.buildEmailHtml();

    await this.resend.emails.send({
      from: process.env.REPORT_EMAIL_FROM || "bot@incomebot.pro",
      to: process.env.REPORT_EMAIL_TO || "you@example.com",
      subject: `📊 Weekly Income Report — $${this.stats.estimatedEarnings.total.toFixed(2)} Earned`,
      html: html,
    });
  }

  buildEmailHtml() {
    const stats = this.stats;
    const recentArticles = stats.articles.slice(-10).reverse();
    const recentRuns = stats.dailyRuns.slice(-7);

    return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: system-ui, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h1 style="color: #2563eb;">📊 Weekly Income Report</h1>
  <p>Week ending: ${new Date().toLocaleDateString()}</p>
  
  <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 20px; margin: 20px 0;">
    <h2 style="margin: 0 0 10px;">💰 Estimated Earnings</h2>
    <table style="width: 100%; border-collapse: collapse;">
      <tr><td>Affiliate Commissions</td><td style="text-align: right;">$${stats.estimatedEarnings.affiliate.toFixed(2)}</td></tr>
      <tr><td>Medium Partner Program</td><td style="text-align: right;">$${stats.estimatedEarnings.medium.toFixed(2)}</td></tr>
      <tr><td>Gumroad Sales</td><td style="text-align: right;">$${stats.estimatedEarnings.gumroad.toFixed(2)}</td></tr>
      <tr style="font-weight: bold; border-top: 2px solid #333;"><td>Total</td><td style="text-align: right;">$${stats.estimatedEarnings.total.toFixed(2)}</td></tr>
    </table>
  </div>

  <div style="margin: 20px 0;">
    <h2>📝 Content Published</h2>
    <p><strong>${stats.totalArticles}</strong> total articles · <strong>${recentRuns.length}</strong> runs this week</p>
    ${recentArticles
      .slice(0, 5)
      .map(
        (a) => `
      <div style="border-left: 3px solid #2563eb; padding: 8px 12px; margin: 8px 0;">
        <strong>${a.title || a.topic}</strong><br/>
        <small>Quality: ${((a.qualityScore || 0.7) * 100).toFixed(0)}% · Published to: ${(a.publishedTo || []).map((p) => p.platform).join(", ") || "pending"}</small>
      </div>
    `,
      )
      .join("")}
  </div>

  <div style="margin: 20px 0;">
    <h2>🎯 Topic Weights (Self-Optimized)</h2>
    <pre style="background: #f5f5f5; padding: 10px; border-radius: 5px;">${JSON.stringify(stats.topicWeights, null, 2)}</pre>
  </div>

  <p style="color: #666; font-size: 12px; margin-top: 30px;">
    🤖 Generated by Income Bot Pro · <a href="${process.env.GITHUB_REPO ? `https://github.com/${process.env.GITHUB_REPO}` : "#"}">View Dashboard</a>
  </p>
</body>
</html>`;
  }
}
